export default {
    C2C: 1,
    GROUP_COMMON: 3,
    GROUP_TIP: 4,
    GROUP_SYSTEM: 5,
    GROUP_TIP2: 6,
    FRIEND_NOTICE: 7,
    PROFILE_NOTICE: 8,
    C2C_COMMON: 9,
    C2C_EVENT: 10,

    CONNECTION_STATUS_INIT: -1,
    CONNECTION_STATUS_ON: 0,
    CONNECTION_STATUS_RECONNECT: 1,
    CONNECTION_STATUS_OFF: 9999,
};
