import keyMirror from 'app/utils/key_mirror';

export default keyMirror({
    CREATE_USER_REQUEST: null,
    CREATE_USER_SUCCESS: null,
    CREATE_USER_FAILURE: null,

    LOGIN_REQUEST: null,
    LOGIN_SUCCESS: null,
    LOGIN_FAILURE: null,

    LOGOUT_REQUEST: null,
    LOGOUT_SUCCESS: null,
    LOGOUT_FAILURE: null,

    PROFILES_REQUEST: null,
    PROFILES_SUCCESS: null,
    PROFILES_FAILURE: null,

    PORTRAIT_PROFILES_REQUEST: null,
    PORTRAIT_PROFILES_SUCCESS: null,
    PORTRAIT_PROFILES_FAILURE: null,

    SNS_PROFILES_REQUEST: null,
    SNS_PROFILES_SUCCESS: null,
    SNS_PROFILES_FAILURE: null,

    RECEIVED_ME: null,
    RECEIVED_PROFILE: null,
    RECEIVED_PROFILES: null,
    RECEIVED_PROFILES_LIST: null,
    RECEIVED_PROFILES_IN_TYPE: null,
    RECEIVED_PROFILES_LIST_IN_TYPE: null,
    RECEIVED_PROFILE_IN_TYPE: null,

    RECEIVED_PORTRAIT_PROFILES: null,
    RECEIVED_SNS_PROFILES: null,
});
